#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'

program :version, '0.0.1'
program :description, 'clears all the derived datas'
 
command :clear do |c|
  c.syntax = 'clearderiveddata clear [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    exec 'rm -rf ~/Library/Developer/Xcode/DerivedData/'
  end
end

